---
name: "Auto Release"

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main
      - master

jobs:
  auto-release:
    name: "Auto Release"
    runs-on: "ubuntu-latest"
    # Only run if CI was successful
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: "‚úèÔ∏è Checkout code"
        uses: actions/checkout@v4

      - name: "üîç Check if manifest.json changed"
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: custom_components/*/manifest.json

      - name: "‚è≠Ô∏è Skip if manifest not changed"
        if: steps.changed-files.outputs.any_changed != 'true'
        run: |
          echo "No manifest.json changes detected. Skipping release."
          exit 0

      - name: "üè∑Ô∏è Get version tag"
        if: steps.changed-files.outputs.any_changed == 'true'
        id: set_var
        run: echo "COMPONENT_VERSION=$(jq -r .version custom_components/*/manifest.json)" >> $GITHUB_ENV

      - name: "üè∑Ô∏è Check if tag exists already"
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: mukunku/tag-exists-action@v1.6.0
        id: "check_tag"
        with:
          tag: "v${{ env.COMPONENT_VERSION }}"

      - name: "‚ùå Cancel if tag is already present"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Tag already present: v${{ env.COMPONENT_VERSION }}. Not creating a new release"

      - name: "üóùÔ∏è Get previous release version"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists != 'true'
        id: last_release
        uses: InsonusK/get-latest-release@v1.1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"

      - name: "üè∑Ô∏è Create new tag"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists != 'true'
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ env.COMPONENT_VERSION }}"
          tag_exists_error: false
          message: "Version ${{ env.COMPONENT_VERSION }}"

      - name: "üóíÔ∏è Generate release changelog"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists != 'true'
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ steps.last_release.outputs.tag_name }}
          headerLabel: "# Notable changes since ${{ steps.last_release.outputs.tag_name }}"
          stripGeneratorNotice: true

      - name: "üìù Write changelog to file"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists != 'true'
        run: echo "${{ steps.changelog.outputs.changelog }}" > RELEASE_CHANGELOG.md

      - name: "üëç Create Stable release"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists != 'true' && contains(env.COMPONENT_VERSION, 'beta') == false
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          body_path: RELEASE_CHANGELOG.md
          name: "Version ${{ env.COMPONENT_VERSION }}"
          tag_name: "v${{ env.COMPONENT_VERSION }}"

      - name: "ü§û Create Beta release"
        if: steps.changed-files.outputs.any_changed == 'true' && steps.check_tag.outputs.exists != 'true' && contains(env.COMPONENT_VERSION, 'beta') == true
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          body_path: RELEASE_CHANGELOG.md
          name: "Version ${{ env.COMPONENT_VERSION }}"
          tag_name: "v${{ env.COMPONENT_VERSION }}"
